# Given: A DNA string s of length at most 1000 bp.

# Return: Four integers (separated by spaces) representing the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s 
#  Note: You must provide your answer in the format shown in the sample output below.

# Sample Dataset
# AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC
# Sample Output
# 20 12 17 21

from Bio.Seq import Seq
my_seq = Seq("CGTCGGACGTGGATAGCTACCTCAGCCGTATGGAACCACTCACCAATGCTGTTCTGCGCTTCACTGCAAAGAACTCAAAGGACTTGTGTCACATCTAGATGCGCCATTTTATCTGCCATCTTCCCATAAATTGGAATGTACCATGTCACTGGTAGGCGTTGGCGGTGGTCAATTCATGCCTTAACTTTCCGACCCAAGCTGCGAACTACTAACGAGTCTCGGCAGCTTTTACCAGCTGTACACTTTATATCCTTATGATGGCACGATACCTTTGACGGTTACCCGAGCTGCGACAAGCGTCGGAGGCTTGTGCCATGATACGCAACTCGCTATCGAATGCCTCGGACTCTTGTGAGGGAGCGCCACATTAGATGATGGAGCGGATCACACGAACTGTTTGACCACACAGCAAAACCTACGAGATCTGATTTTGTCACAACACGGCGGCGTGGCCCGACCAACTTATTGAGACCTTTGTATTTGTCCCATGTGGCCATAATACAAAAAAACCTAGCCGCTCTCCGGTCTAGCCCATCATTGACGGGCTAACGGGATGCGGGTAAGGTCTCTACCCTAGTGGATATCATCCTCTAACCTCCCGTTCAGAAGGGCGTTGTTTCGGACCTGTGAGGTGTCACGATAATGATGGTTTCTCTACCCGTACGCGCGCTCTCAGCACCGAAGATCACATCGGGGCAACTCTAGCTCATGTTGACGTAACTGTGGTGTACTGATCAGTTTACATCACTCCCATATATAAGTCGCTCGTCTCTATTTGCGATGTTCTATTTGCTTTGATATAGGTTTTACTGATATAGTCGAATTTTGATCTGACTGACGAGGTTCATTTACTCTATATCTAATAGGATTAAACTCCGT")
lst = list()
lst.append(my_seq.count('A')),
lst.append(my_seq.count('C')),
lst.append(my_seq.count('G'))
lst.append(my_seq.count('T'))
print(lst)
string =''
for x in lst :
    string = string + str(x) + ' '
print(string)